-- MySQL Script generated by MySQL Workbench
-- Tue Sep 13 11:16:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema orquideas_san_martin_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orquideas_san_martin_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orquideas_san_martin_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `orquideas_san_martin_db` ;

-- -----------------------------------------------------
-- Table `orquideas_san_martin_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orquideas_san_martin_db`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orquideas_san_martin_db`.`climas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orquideas_san_martin_db`.`climas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoDeClima` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orquideas_san_martin_db`.`tamaño`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orquideas_san_martin_db`.`tamaño` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tamaño` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orquideas_san_martin_db`.`orquideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orquideas_san_martin_db`.`orquideas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `clima_id` INT(11) NOT NULL,
  `precio` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  `tamaño_id` INT(11) NOT NULL,
  `disponibilidad` VARCHAR(100) NOT NULL,
  `flor` VARCHAR(100) NOT NULL,
  `imagen1` VARCHAR(45) NOT NULL,
  `imagen2` VARCHAR(45) NOT NULL,
  `imagen3` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `clima_idx` (`clima_id` ASC) VISIBLE,
  INDEX `categoria_idx` (`categoria_id` ASC, `tamaño_id` ASC) VISIBLE,
  INDEX `tamaño_idx` (`tamaño_id` ASC) VISIBLE,
  CONSTRAINT `clima`
    FOREIGN KEY (`clima_id`)
    REFERENCES `orquideas_san_martin_db`.`climas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tamaño`
    FOREIGN KEY (`tamaño_id`)
    REFERENCES `orquideas_san_martin_db`.`tamaño` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `orquideas_san_martin_db`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orquideas_san_martin_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orquideas_san_martin_db`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cedulaDeCiudadania` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contraseñaConfimacion` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedulaDeCiudadania_UNIQUE` (`cedulaDeCiudadania` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
