-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 12:52:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 5bPvv5pu0J
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 5bPvv5pu0J
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `5bPvv5pu0J` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `5bPvv5pu0J` ;

-- -----------------------------------------------------
-- Table `5bPvv5pu0J`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5bPvv5pu0J`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `5bPvv5pu0J`.`climas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5bPvv5pu0J`.`climas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoDeClima` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `5bPvv5pu0J`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5bPvv5pu0J`.`secciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `5bPvv5pu0J`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5bPvv5pu0J`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoDeDocumento` VARCHAR(160) NOT NULL,
  `documento` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `contrasenia` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contraseniaConf` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedulaDeCiudadania_UNIQUE` (`documento` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `5bPvv5pu0J`.`tamanios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5bPvv5pu0J`.`tamanios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tamanio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `5bPvv5pu0J`.`orquideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `5bPvv5pu0J`.`orquideas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `clima_id` INT NOT NULL,
  `precio` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `categoria_id` INT NOT NULL,
  `tamanio_id` INT NOT NULL,
  `disponibilidad` VARCHAR(100) NOT NULL,
  `flor` VARCHAR(100) NOT NULL,
  `imagen1` VARCHAR(500) NOT NULL,
  `imagen2` VARCHAR(500) NOT NULL,
  `imagen3` VARCHAR(500) NOT NULL,
  `secciondehome_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `clima_idx` (`clima_id` ASC) VISIBLE,
  INDEX `categoria_idx` (`categoria_id` ASC, `tamanio_id` ASC) ,
  INDEX `tamaño_idx` (`tamanio_id` ASC) VISIBLE,
  INDEX `fk_orquideas_secciondehome1_idx` (`secciondehome_id` ASC) ,
  INDEX `fk_orquideas_usuarios1_idx` (`usuarios_id` ASC) ,
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `5bPvv5pu0J`.`categorias` (`id`),
  CONSTRAINT `clima`
    FOREIGN KEY (`clima_id`)
    REFERENCES `5bPvv5pu0J`.`climas` (`id`),
  CONSTRAINT `fk_orquideas_secciondehome1`
    FOREIGN KEY (`secciondehome_id`)
    REFERENCES `5bPvv5pu0J`.`secciones` (`id`),
  CONSTRAINT `fk_orquideas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `5bPvv5pu0J`.`usuarios` (`id`),
  CONSTRAINT `tamaño`
    FOREIGN KEY (`tamanio_id`)
    REFERENCES `5bPvv5pu0J`.`tamanios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 824
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
